FROM node:20.16.0-alpine

WORKDIR /app

ARG SERVICE_PORT=6000
ARG NEXT_PUBLIC_API_BASE_URL
ARG NEXT_PUBLIC_WEB_PATH
ARG NEXT_PUBLIC_POS_PATH
ARG NEXT_PUBLIC_TINYMCE_API_KEY

ENV SERVICE_PORT=${SERVICE_PORT}
ENV NEXT_PUBLIC_API_BASE_URL=${NEXT_PUBLIC_API_BASE_URL}
ENV NEXT_PUBLIC_WEB_PATH=${NEXT_PUBLIC_WEB_PATH}
ENV NEXT_PUBLIC_POS_PATH=${NEXT_PUBLIC_POS_PATH}
ENV NEXT_PUBLIC_TINYMCE_API_KEY=${NEXT_PUBLIC_TINYMCE_API_KEY}
# RUN echo "Based on commit: $NEXT_PUBLIC_BASE_API_URL"

COPY package*.json ./
COPY . .
RUN yarn install

RUN yarn build

EXPOSE $SERVICE_PORT

# Start the application
CMD ["yarn", "start"]